/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FATTOREX_H_RPCGEN
#define _FATTOREX_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAXCANDIDATI 15
#define MAXGIUDICI 5

struct Candidato {
	char candidato[32];
	char giudice[32];
	char categoria;
	char nomeFile[32];
	char fase;
	int voto;
};
typedef struct Candidato Candidato;
#ifdef __cplusplus
extern "C" bool_t xdr_Candidato(XDR *, Candidato*);
#elif __STDC__
extern  bool_t xdr_Candidato(XDR *, Candidato*);
#else /* Old Style C */
bool_t xdr_Candidato();
#endif /* Old Style C */


struct Candidati {
	Candidato candidato[MAXCANDIDATI];
};
typedef struct Candidati Candidati;
#ifdef __cplusplus
extern "C" bool_t xdr_Candidati(XDR *, Candidati*);
#elif __STDC__
extern  bool_t xdr_Candidati(XDR *, Candidati*);
#else /* Old Style C */
bool_t xdr_Candidati();
#endif /* Old Style C */


struct Giudice {
	char nomeGiudice[32];
	int punteggio;
};
typedef struct Giudice Giudice;
#ifdef __cplusplus
extern "C" bool_t xdr_Giudice(XDR *, Giudice*);
#elif __STDC__
extern  bool_t xdr_Giudice(XDR *, Giudice*);
#else /* Old Style C */
bool_t xdr_Giudice();
#endif /* Old Style C */


struct Output {
	Giudice giudici[MAXGIUDICI];
};
typedef struct Output Output;
#ifdef __cplusplus
extern "C" bool_t xdr_Output(XDR *, Output*);
#elif __STDC__
extern  bool_t xdr_Output(XDR *, Output*);
#else /* Old Style C */
bool_t xdr_Output();
#endif /* Old Style C */


struct Input {
	char candidato[32];
	char operazione;
};
typedef struct Input Input;
#ifdef __cplusplus
extern "C" bool_t xdr_Input(XDR *, Input*);
#elif __STDC__
extern  bool_t xdr_Input(XDR *, Input*);
#else /* Old Style C */
bool_t xdr_Input();
#endif /* Old Style C */


#define FATTOREX ((rpc_uint)0x20000013)
#define FATTOREXVERS ((rpc_uint)1)

#ifdef __cplusplus
#define CLASSIFICA_GIUDICI ((rpc_uint)1)
extern "C" Output * classifica_giudici_1(void *, CLIENT *);
extern "C" Output * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO ((rpc_uint)2)
extern "C" Candidati * esprimi_voto_1(Input *, CLIENT *);
extern "C" Candidati * esprimi_voto_1_svc(Input *, struct svc_req *);

#elif __STDC__
#define CLASSIFICA_GIUDICI ((rpc_uint)1)
extern  Output * classifica_giudici_1(void *, CLIENT *);
extern  Output * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO ((rpc_uint)2)
extern  Candidati * esprimi_voto_1(Input *, CLIENT *);
extern  Candidati * esprimi_voto_1_svc(Input *, struct svc_req *);

#else /* Old Style C */
#define CLASSIFICA_GIUDICI ((rpc_uint)1)
extern  Output * classifica_giudici_1();
extern  Output * classifica_giudici_1_svc();
#define ESPRIMI_VOTO ((rpc_uint)2)
extern  Candidati * esprimi_voto_1();
extern  Candidati * esprimi_voto_1_svc();
#endif /* Old Style C */

#endif /* !_FATTOREX_H_RPCGEN */
